name: 00_Initial_Setup_First_Step

on:
  push:
    branches: [ master, fb-** ]
    paths:                
      - '03_IaC/00_AzureCLI/MyDeploymentValues.txt'  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Initial_Setup_PublicIP_ACR_RG:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Load env variable from file using pwsh'
      shell: pwsh
      run: 03_IaC/00_AzureCLI/10_LoadEnvVariables.ps1
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true    
    - name: 'Run Initial Setup powershell'
      shell: pwsh
      run: 03_IaC/00_AzureCLI/00_InitialSetup_iac.ps1
      id: InitialSetup    
